# Generated by Django 3.1.1 on 2020-09-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesthelp',
            options={'ordering': ['title'], 'verbose_name': 'Help Request', 'verbose_name_plural': 'Help Requests'},
        ),
        migrations.AlterField(
            model_name='requesthelp',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دعم مالى'), (2, 'دعم وظيفى'), (3, 'بلا مأوى')], help_text='نوع المساعده', null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='RequestConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('reason', models.TextField(blank=True, help_text='سبب حالة الرفض', null=True, verbose_name='Reason')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.requesthelp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Confirm',
                'verbose_name_plural': 'Requests Confirm',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'تبرع مالى'), (2, 'تبرع ملابس'), (3, 'تبرع أجهزه')], help_text='نوع التبرع', null=True, verbose_name='Type')),
                ('payment', models.PositiveSmallIntegerField(choices=[(1, ' شهرى'), (2, ' فورى'), (3, 'اسبوعى')], help_text='نوع المساعده', null=True, verbose_name='Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['name'],
            },
        ),
    ]
